# Generated by Django 5.0.2 on 2024-02-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_info', to='app.authordetails'),
        ),
    ]
